import {rooms,today,addDays,nights,validateStay,fixtures,remaining,quote,validateGuest} from './booking.js';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'LKR '+n.toLocaleString('en-US');
const date=d=>new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(d+'T00:00:00Z'));
let demoBookings=[];
try {const saved=JSON.parse(sessionStorage.getItem('tide-palm-inventory')||'[]');if(Array.isArray(saved))demoBookings=saved.filter(b=>rooms.some(r=>r.id===b.roomId)&&typeof b.checkin==='string'&&typeof b.checkout==='string'&&b.quantity===1);}catch{}
let stay={checkin:addDays(today(),1),checkout:addDays(today(),3),adults:2,children:0};
let draft=null,stage=1;
const bookings=()=>[...fixtures(),...demoBookings];
function availability(room){return remaining(room,stay,bookings());}
$('#checkin').min=today();$('#checkout').min=addDays(today(),1);$('#checkin').max=addDays(today(),364);$('#checkout').max=addDays(today(),365);
$('#checkin').value=stay.checkin;$('#checkout').value=stay.checkout;
function readStay(){return {checkin:$('#checkin').value,checkout:$('#checkout').value,adults:Number($('#adults').value),children:Number($('#children').value)};}
function setError(selector,message){const el=$(selector);el.textContent=message;el.hidden=!message;}
function renderRooms(){
 const error=validateStay(stay);if(error){$('#availability-status').textContent='Update your dates to see availability.';return;}
 let availableCount=0;
 $('#room-grid').innerHTML=rooms.map(room=>{
  const stock=availability(room),fits=stay.adults+stay.children<=room.capacity,enabled=stock>0&&fits;
  if(enabled)availableCount++;
  const q=quote(room,stay);
  return `<article class="room-card"><div class="room-photo ${room.id}" role="img" aria-label="Concept image for ${room.name}"><span class="room-badge">${!fits?'Up to '+room.capacity+' guests':stock?'Available · '+stock+' '+(stock===1?'room':'rooms'):'Unavailable for these dates'}</span></div><div class="room-content"><p class="eyebrow">${room.tag}</p><h3>${room.name}</h3><div class="room-spec"><span>♙ ${room.capacity} guests</span><span>▱ ${room.bed}</span><span>${room.size} m²</span></div><p class="room-description">${room.description}</p><div class="features">${room.features.map(f=>`<span>${f}</span>`).join('')}</div><div class="room-price"><strong>${money(room.rate)}</strong><span>/ night</span></div><p class="stay-total">${money(q.total)} for ${q.nights} nights · taxes included</p><button class="button" data-room="${room.id}" ${enabled?'':'disabled'}>${enabled?'Choose this room':!fits?'Choose a larger room':'Unavailable'}<span>${enabled?'↗':'—'}</span></button></div></article>`;
 }).join('');
 $('#availability-status').textContent=`${availableCount} room types available · ${date(stay.checkin)} – ${date(stay.checkout)} · ${stay.adults+stay.children} guests`;
 if(!availableCount)$('#room-grid').insertAdjacentHTML('afterbegin','<div class="no-results"><h3>A different date, a little more room.</h3><p>No room fits this search. Try other dates or reduce the number of guests. This prototype supports one room per booking.</p></div>');
}
$('#checkin').addEventListener('change',()=>{const v=$('#checkin').value;if(v){$('#checkout').min=addDays(v,1);if($('#checkout').value<=v)$('#checkout').value=addDays(v,1);}});
$('#search-form').addEventListener('submit',e=>{e.preventDefault();const next=readStay(),error=validateStay(next);setError('#search-error',error);if(error)return;stay=next;renderRooms();$('#rooms').scrollIntoView({behavior:'smooth',block:'start'});});
for(const s of ['#checkin','#checkout','#adults','#children'])$(s).addEventListener('change',()=>{$('#availability-status').textContent='Dates or guests changed. Check availability to update your rooms.';document.querySelectorAll('[data-room]').forEach(b=>{b.disabled=true;});});
$('#room-grid').addEventListener('click',e=>{const b=e.target.closest('[data-room]');if(!b)return;const room=rooms.find(r=>r.id===b.dataset.room);if(!room||!availability(room)||stay.adults+stay.children>room.capacity)return;draft={room,stay:{...stay},guest:{firstName:'',lastName:'',email:'',phone:'',country:'Sri Lanka',requests:''},extras:{breakfast:false,transfer:false},method:'card',outcome:'success',complete:false};stage=1;renderBooking();$('#booking-dialog').showModal();$('#booking-dialog').scrollTop=0;});
function setStage(n){stage=n;document.querySelectorAll('[data-step]').forEach(el=>{el.classList.toggle('active',Number(el.dataset.step)===n);if(Number(el.dataset.step)===n)el.setAttribute('aria-current','step');else el.removeAttribute('aria-current');});}
function summary(){const {room,stay:s,extras}=draft,q=quote(room,s,extras);return `<aside class="summary" aria-label="Booking summary"><div class="summary-photo room-photo ${room.id}"></div><p class="eyebrow">YOUR STAY AT A GLANCE</p><h3>${room.name}</h3><div class="summary-dates">${date(s.checkin)} → ${date(s.checkout)}<span>${q.nights} nights · ${s.adults} ${s.adults===1?'adult':'adults'}${s.children?' · '+s.children+' '+(s.children===1?'child':'children'):''} · 1 room</span></div><div class="price-row"><span>${money(room.rate)} × ${q.nights} nights</span><strong>${money(q.roomTotal)}</strong></div>${q.breakfast?`<div class="price-row"><span>Breakfast · all guests</span><strong>${money(q.breakfast)}</strong></div>`:''}${q.transfer?`<div class="price-row"><span>Airport pickup · one way</span><strong>${money(q.transfer)}</strong></div>`:''}<div class="price-row"><span>Sample taxes & service</span><strong>Included</strong></div><div class="price-row total"><span>Total stay</span><strong data-testid="booking-total">${money(q.total)}</strong></div><p class="subtle">Charged currency: LKR. Overseas card issuers may apply conversion or fees when live payments are enabled.</p><div class="summary-note"><p class="subtle">Sample policy: free cancellation until 7 days before arrival; then one night charged. Check-in 14:00 · Check-out 11:00 (Sri Lanka time).</p><p class="subtle">Demonstration only. No real room is reserved.</p></div></aside>`;}
function refreshSummary(){const old=$('.summary');if(old)old.outerHTML=summary();}
function renderBooking(){setStage(stage);if(stage===1)renderDetails();if(stage===2)renderReview();}
function renderDetails(){const g=draft.guest;$('#booking-content').innerHTML=`<div class="checkout-layout"><form id="guest-form" class="checkout-form" novalidate><h3>Who’s coming to stay?</h3><p class="subtle">Use sample details to try the booking. Required fields are marked *.</p><div class="form-grid"><label class="field">First name *<input name="firstName" autocomplete="given-name" maxlength="70" required value="${esc(g.firstName)}"></label><label class="field">Last name *<input name="lastName" autocomplete="family-name" maxlength="70" required value="${esc(g.lastName)}"></label><label class="field wide">Email address *<input name="email" autocomplete="email" type="email" maxlength="160" required value="${esc(g.email)}"><span class="help">A live booking would send confirmation here. This demo sends no email.</span></label><label class="field wide">Phone number with country code *<input name="phone" autocomplete="tel" type="tel" maxlength="25" placeholder="+94 77 123 4567" required value="${esc(g.phone)}"></label><label class="field wide">Country of residence *<input name="country" autocomplete="country-name" list="countries" required maxlength="80" value="${esc(g.country)}"><datalist id="countries"><option>Sri Lanka</option><option>India</option><option>United Kingdom</option><option>Germany</option><option>France</option><option>Australia</option><option>United States</option><option>Canada</option><option>Netherlands</option><option>United Arab Emirates</option><option>Japan</option><option>China</option><option>Maldives</option><option>Singapore</option></datalist><span class="help">Choose a suggestion or type any country.</span></label><label class="field wide">Special requests <span class="subtle">(optional)</span><textarea name="requests" maxlength="500" placeholder="Arrival time, dietary needs, or a little something else…">${esc(g.requests)}</textarea><span class="help">Requests are subject to confirmation in a live booking.</span></label></div><fieldset class="extras"><legend>Make it a little more yours</legend><label class="check-row"><input type="checkbox" id="breakfast" ${draft.extras.breakfast?'checked':''}><span>Breakfast for everyone<small>LKR 1,800 per guest, per night · sample rate</small></span></label><label class="check-row"><input type="checkbox" id="transfer" ${draft.extras.transfer?'checked':''}><span>Airport pickup<small>LKR 18,000 per booking · one way · sample rate</small></span></label></fieldset><p class="error" id="guest-error" role="alert" hidden></p><button class="button full" type="submit">Continue to checkout <span>→</span></button><p class="subtle" style="margin-top:10px">No passport or card details needed.</p></form>${summary()}</div>`;
 $('#guest-form').addEventListener('input',captureGuest);
 for(const key of ['breakfast','transfer'])$('#'+key).addEventListener('change',e=>{draft.extras[key]=e.target.checked;refreshSummary();});
 $('#guest-form').addEventListener('submit',e=>{e.preventDefault();captureGuest();const error=validateGuest(draft.guest);setError('#guest-error',error);if(error){$('#guest-error').scrollIntoView({block:'center'});return;}stage=2;renderBooking();$('#booking-dialog').scrollTop=0;$('#booking-title').focus();});
}
function captureGuest(){if(!$('#guest-form'))return;const d=new FormData($('#guest-form'));draft.guest=Object.fromEntries(['firstName','lastName','email','phone','country','requests'].map(k=>[k,String(d.get(k)||'').trim()]));}
function renderReview(){const g=draft.guest;$('#booking-content').innerHTML=`<div class="checkout-layout"><form id="payment-form" class="payment-form" novalidate><h3>One last little detail.</h3><p class="subtle">Review your stay and choose how you’d like to pay.</p><div class="guest-review"><strong>${esc(g.firstName)} ${esc(g.lastName)}</strong>${esc(g.email)}<br>${esc(g.phone)} · ${esc(g.country)}${g.requests?'<p class="subtle">Request: '+esc(g.requests)+'</p>':''}<button type="button" class="back-link" id="edit-guest">Edit guest details & extras</button></div><label class="payment-choice"><input type="radio" name="method" value="card" ${draft.method==='card'?'checked':''}><span><strong>Pay by card</strong><small>Local & international cards · simulated checkout</small></span></label><label class="payment-choice"><input type="radio" name="method" value="property" ${draft.method==='property'?'checked':''}><span><strong>Pay at the property</strong><small>Full amount due on arrival · demo reservation only</small></span></label><div id="payment-sub"></div><label class="check-row terms"><input type="checkbox" id="terms" required><span>I accept the sample cancellation policy and understand this is a demo with no real reservation or payment.</span></label><p class="error" id="payment-error" role="alert" hidden></p><div class="button-row"><button type="button" class="button outline" id="back-details">← Back</button><button class="button" type="submit" id="complete-booking">Complete demo booking →</button></div><p class="subtle" style="margin-top:12px">No payment provider is connected. No card information is collected.</p></form>${summary()}</div>`;
 renderPaymentSub();
 $('#edit-guest').onclick=$('#back-details').onclick=()=>{stage=1;renderBooking();$('#booking-dialog').scrollTop=0;};
 document.querySelectorAll('[name="method"]').forEach(el=>el.onchange=e=>{draft.method=e.target.value;renderPaymentSub();setError('#payment-error','');});
 $('#payment-form').onsubmit=e=>{e.preventDefault();completeBooking();};
}
function renderPaymentSub(){const q=quote(draft.room,draft.stay,draft.extras);$('#payment-sub').innerHTML=draft.method==='card'?`<div class="payment-sub"><h4>Card payment simulator</h4><p class="subtle">Amount: ${money(q.total)}. In the live site, a hosted payment page would securely collect card details.</p><label class="field" style="margin-top:10px">Demo payment result<select id="payment-outcome"><option value="success">Successful payment</option><option value="decline">Declined payment</option><option value="cancel">Guest cancels payment</option></select></label></div>`:`<div class="notice">Nothing due now. ${money(q.total)} would be payable at the property. This demo does not reserve a real room.</div>`;
 if($('#payment-outcome')){$('#payment-outcome').value=draft.outcome;$('#payment-outcome').onchange=e=>draft.outcome=e.target.value;}
}
function completeBooking(){
 if(draft.complete)return;
 if(!$('#terms').checked){setError('#payment-error','Please accept the sample policy before continuing.');return;}
 const error=validateStay(draft.stay)||validateGuest(draft.guest);if(error){setError('#payment-error',error);return;}
 if(draft.stay.adults+draft.stay.children>draft.room.capacity||remaining(draft.room,draft.stay,bookings())<1){setError('#payment-error','This room is no longer available for your party and dates. Close checkout and choose another room.');return;}
 if(draft.method==='card'&&draft.outcome!=='success') {setError('#payment-error',draft.outcome==='decline'?'Demo payment declined. No payment or reservation was made. Choose “Successful payment” to retry, or pay at the property.':'Demo payment cancelled. Nothing was charged or reserved. You can retry or choose pay at the property.');return;}
 draft.complete=true;draft.reference='DEMO-'+crypto.randomUUID().slice(0,8).toUpperCase();
 demoBookings.push({roomId:draft.room.id,checkin:draft.stay.checkin,checkout:draft.stay.checkout,quantity:1});
 try{sessionStorage.setItem('tide-palm-inventory',JSON.stringify(demoBookings));}catch{}
 setStage(3);const q=quote(draft.room,draft.stay,draft.extras);
 $('#booking-content').innerHTML=`<div class="success"><div class="success-icon">✓</div><p class="eyebrow">A LITTLE ESCAPE, ALL PLANNED</p><h3>Your demo booking is complete.</h3><p class="subtle">Thank you, ${esc(draft.guest.firstName)}. This is a demonstration confirmation. No real room has been booked, no money has been charged, and no email has been sent.</p><div class="reference">${draft.reference}</div><div class="receipt"><div class="price-row"><span>Your room</span><strong>${draft.room.name}</strong></div><div class="price-row"><span>Check-in</span><strong>${date(draft.stay.checkin)} · 14:00</strong></div><div class="price-row"><span>Check-out</span><strong>${date(draft.stay.checkout)} · 11:00</strong></div><div class="price-row"><span>Guests</span><strong>${draft.stay.adults} adults · ${draft.stay.children} children</strong></div><div class="price-row total"><span>Total stay</span><strong>${money(q.total)}</strong></div><div class="price-row"><span>Payment status</span><strong>${draft.method==='card'?'Simulated payment success':'Pay at property · unpaid'}</strong></div><div class="price-row"><span>Actually charged</span><strong>LKR 0</strong></div></div><p class="subtle">Demo availability has been updated in this browser tab. Your guest details are held only in page memory and clear on refresh.</p><div class="button-row"><button class="button outline" id="download-receipt">Download demo summary ↓</button><button class="button" id="return-rooms">Back to rooms →</button></div></div>`;
 $('#download-receipt').onclick=downloadReceipt;$('#return-rooms').onclick=()=>{$('#booking-dialog').close();$('#rooms').scrollIntoView({behavior:'smooth'});};renderRooms();$('#booking-dialog').scrollTop=0;
}
function downloadReceipt(){const q=quote(draft.room,draft.stay,draft.extras);const text=`TIDE & PALM — DEMO BOOKING SUMMARY\nNot a real reservation or payment receipt\n\nReference: ${draft.reference}\nGuest: ${draft.guest.firstName} ${draft.guest.lastName}\nEmail: ${draft.guest.email}\nPhone: ${draft.guest.phone}\nCountry: ${draft.guest.country}\nRoom: ${draft.room.name}\nCheck-in: ${draft.stay.checkin}, 14:00 Sri Lanka time\nCheck-out: ${draft.stay.checkout}, 11:00 Sri Lanka time\nAdults: ${draft.stay.adults}; children: ${draft.stay.children}\nRoom total: ${money(q.roomTotal)}\nBreakfast: ${money(q.breakfast)}\nAirport pickup: ${money(q.transfer)}\nTaxes and service: included (sample)\nTotal: ${money(q.total)}\nPayment: ${draft.method==='card'?'Simulated success':'Due at property (demo)'}\nActually charged: LKR 0\nRequests: ${draft.guest.requests||'None'}\n\nNo real booking or payment was made. No email has been sent.\nSample policy: free cancellation until 7 days before arrival, then one night charged.\nAll property details, facilities, prices and policies require owner approval.\n`;
const blob=new Blob([text],{type:'text/plain;charset=utf-8'}),a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=draft.reference+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#close-booking').onclick=()=>$('#booking-dialog').close();
$('#booking-dialog').addEventListener('close',()=>{draft=null;stage=1;});
const info={
 about:()=>`<p class="eyebrow">PRIVATE WORKING PROTOTYPE</p><h2 id="info-title">A first look at your villa.</h2><p>“Tide & Palm” is a temporary name for the Halawatha / Chilaw hotel project. Imagery is AI-generated concept photography. Rooms, amenities, rates, inventory, contact details and policies are samples, not statements about an operating hotel.</p><h3>Try a complete booking</h3><p>Choose dates, check room capacity, add guest details and optional extras, then try a card payment outcome or pay at the property. No gateway is registered, connected or activated, and no email is sent.</p><h3>Availability & privacy</h3><p>The sample inventory contains 3 Garden Rooms, 2 Poolside Suites and 1 Family Villa. Completed demo stays reduce inventory in this browser tab only. There is no shared hotel calendar or live reservation system. Guest details are held in page memory, not sent to a server, and clear on refresh. Use fictional details.</p><p>Try the Family Villa between ${date(addDays(today(),7))} and ${date(addDays(today(),10))} to see an unavailable room. The Poolside Suite is unavailable from ${date(addDays(today(),14))} to ${date(addDays(today(),16))}. Check-out dates do not occupy that night.</p><button class="button outline" id="reset-demo" style="margin-top:22px">Reset demo availability</button><p id="reset-status" class="subtle" role="status"></p>`,
 details:()=>`<p class="eyebrow">GOOD TO KNOW</p><h2 id="info-title">The little details.</h2><p>All of the following are proposed policies for this prototype and need hotel-owner approval.</p><h3>Arrival & departure</h3><p>Check-in from 14:00 and check-out by 11:00, using Sri Lanka time. The exact address, directions and reception contact will be added when the property is confirmed.</p><h3>Guests & rooms</h3><p>One room per booking, with at least one adult. Garden Room: up to 2 guests. Poolside Suite: up to 3. Family Villa: up to 5. Every child counts toward occupancy; breakfast uses the same sample rate for all guests. Group and infant policies remain to be finalized.</p><h3>Rates & cancellation</h3><p>Prices are in Sri Lankan rupees (LKR). The displayed sample total includes taxes and service; no extra tax is added. Proposed cancellation: free until 7 days before arrival; after that, one night charged. The real tax treatment and cancellation rules must be confirmed before launch.</p><h3>Optional extras</h3><p>Breakfast: LKR 1,800 per person per night. One-way airport pickup: LKR 18,000 per booking. Both are illustrative rates, subject to the hotel’s approval.</p>`,
 payments:()=>`<p class="eyebrow">OWNER NOTES · CHECKED 19 SEPTEMBER 2026</p><h2 id="info-title">A practical path to payments.</h2><p>Recommendation: shortlist PayHere Plus for a straightforward villa launch, and compare a WEBXPAY quote if foreign-card volume or settlement needs justify it. No provider has been registered or activated.</p><div class="comparison"><table><thead><tr><th>Option</th><th>Published cost</th><th>Practical fit</th></tr></thead><tbody><tr><td><a href="https://www.payhere.lk/fees/" target="_blank" rel="noopener noreferrer">PayHere Lite</a></td><td>No monthly fee; 3.30% base processing.</td><td>LKR 50,000 per payment and 200,000/month cap. Multi-night stays can exceed this.</td></tr><tr><td><a href="https://www.payhere.lk/fees/" target="_blank" rel="noopener noreferrer">PayHere Plus</a></td><td>LKR 3,990/month; 2.99% base processing.</td><td>LKR 250,000 per payment and 3 million/month cap. Strong initial candidate.</td></tr><tr><td><a href="https://www.webxpay.com/pricing" target="_blank" rel="noopener noreferrer">WEBXPAY Starter</a></td><td>LKR 10,000/12 months; Visa/Mastercard 3.80% domestic, 4.85% foreign.</td><td>Published unlimited monthly payments. Confirm currencies, settlement and hotel eligibility with a written quote.</td></tr></tbody></table></div><p>PayHere lists +1% for foreign-currency payments and +0.5% for premium card brands. Those are separate from currency conversion by a guest’s card issuer. WEBXPAY’s foreign-card pricing and multi-currency activation are separate items; get the correct package confirmed.</p><h3>Before a live launch</h3><p>After owner approval: apply under the hotel’s legal business, confirm its settlement account and hospitality eligibility, approve the rate and cancellation policies, then integrate hosted checkout. Live inventory needs server-side room holds; payment amounts and signed gateway notifications must be verified on the server before confirming a booking. A browser redirect alone must never mark a booking as paid.</p><p><a href="https://support.payhere.lk/api-&-mobile-sdk/checkout-api" target="_blank" rel="noopener noreferrer">PayHere checkout documentation</a> · <a href="https://www.webxpay.com/pricing" target="_blank" rel="noopener noreferrer">WEBXPAY pricing</a></p>`
};
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{const key=b.dataset.open;$('#info-content').innerHTML=info[key]();$('#info-dialog').showModal();$('#info-dialog').scrollTop=0;if(key==='about')$('#reset-demo').onclick=()=>{demoBookings=[];try{sessionStorage.removeItem('tide-palm-inventory');}catch{}renderRooms();$('#reset-status').textContent='Demo bookings cleared. Original sample availability restored.';};});
$('.info-close').onclick=()=>$('#info-dialog').close();
renderRooms();
